#ifndef MATHLIB_VERSION_H
#define MATHLIB_VERSION_H

/* v11S CLOSURE IP-22: version alignment */

#define MATHLIB_VERSION_MAJOR 11
#define MATHLIB_VERSION_MINOR 0
#define MATHLIB_VERSION_PATCH 0
#define MATHLIB_VERSION_RELEASE_CANDIDATE 1

#define MATHLIB_VERSION_STRING "11.0.0-rc1 (v11S closure candidate)"
#define MATHLIB_VERSION_TAG "v11S"

#endif /* MATHLIB_VERSION_H */
