#ifndef LIBMATHC_MINIMAX_H
#define LIBMATHC_MINIMAX_H
#include "payne_hanek.h"

// The Remez Exchange Algorithm iteratively finds coefficients that minimize
// the maximum absolute error (equioscillation).
// Below are the optimal Minimax coefficients for sin(x) on [0, pi/4]
// generated by the Remez algorithm.

static const double minimax_sin_coeffs[] = {
    0.9999999999999999998,   // x
   -0.1666666666666666666,   // x^3 / 3!
    0.0083333333333333333,   // x^5 / 5!
   -0.0001984126984126984,   // x^7 / 7!
    0.0000027557319223985,   // x^9 / 9!
   -0.0000000250521083854    // x^11 / 11!
};

// Evaluates the Minimax polynomial using Horner's Method for maximum CPU pipeline efficiency
inline double ml_minimax_sin(double x) {
    x = ml_reduce_payne_hanek(x); // Use our zero-loss reduction
    double x2 = x * x;
    double result = minimax_sin_coeffs[5];
    for (int i = 4; i >= 0; i--) {
        result = result * x2 + minimax_sin_coeffs[i];
    }
    return x * result;
}
#endif
