#ifndef MATHLIB_VERSION_H
#define MATHLIB_VERSION_H

#define MATHLIB_VERSION_MAJOR 11
#define MATHLIB_VERSION_MINOR 0
#define MATHLIB_VERSION_PATCH 0
#define MATHLIB_VERSION_STRING "11.0.0"

#endif // MATHLIB_VERSION_H
