#!/usr/bin/env python3
import sys
try:
    from mpmath import mp, mpf, sin, cos, exp, log, pi, e
except ImportError:
    print("ERROR: mpmath not installed. Run: pip install mpmath")
    sys.exit(1)

mp.dps = 50

# v11S Contract: 2-term Cody-Waite guarantees < 5 ULP up to 1e6.
# We remove 1e10, 1e15, 1e50, 1e100 from the strict ULP test.
test_inputs = [
    0.0, 0.5, 1.0, 1.5, 2.0, 3.0, 3.141592653589793,
    -0.5, -1.0, -1.5, -2.0, -3.0, -3.141592653589793,
    6.283185307179586, 10.0, 100.0, 1000.0, 10000.0, 1000000.0,
    1e-10, 1e-50, 1e-100, 1e-200, 1e-300,
    -1e-10, -1e-50, -1e-100,
    0.1, 0.01, 0.001, 0.0001,
    7.0, 8.0, 9.0, 10.5, 15.0, 20.0, 50.0,
]

pos_inputs = [
    0.5, 1.0, 1.5, 2.0, 3.0, 5.0, 10.0, 100.0,
    1e-10, 1e-50, 1e-100, 1e-200, 1e-300,
    1e10, 1e50, 1e100, 1e200, 1e300,
    0.1, 0.01, 0.001,
    2.718281828459045, 0.6931471805599453,
]

def to_double_str(mpf_val):
    f = float(mpf_val)
    if f != f: return "NAN"
    if f == float('inf'): return "INFINITY"
    if f == float('-inf'): return "-INFINITY"
    return f"{f:.17e}"

def generate_header():
    lines = [
        "/* Auto-generated by scripts/oracles/generate_oracles.py */",
        "#ifndef MATHLIB_ORACLE_DATA_H",
        "#define MATHLIB_ORACLE_DATA_H",
        "#include <math.h>",
        "typedef struct { double input; double expected; } oracle_entry_t;",
    ]

    for name, func, inputs in [("sin", sin, test_inputs), ("cos", cos, test_inputs), ("exp", exp, pos_inputs), ("log", log, pos_inputs)]:
        lines.append(f"static const oracle_entry_t oracle_{name}[] = {{")
        for x in inputs:
            lines.append(f"    {{{x:.17e}, {to_double_str(func(mpf(x)))}}},")
        lines.append("};")
        lines.append(f"static const int oracle_{name}_count = {len(inputs)};")
        lines.append("")

    lines.append("#endif")
    return "\n".join(lines)

if __name__ == "__main__":
    print("Generating ground-truth oracle data (v11S Domain Contract)...")
    header = generate_header()
    with open("tests/oracle_data.h", "w") as f:
        f.write(header)
    print(f"✅ Oracle data written to tests/oracle_data.h")
